version: 2.1

orbs: 
  terraform: circleci/terraform@3.0.1

workflows:
  main:
    jobs:
      - terraform/fmt:
          checkout: true
      - terraform/validate:
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate