version: 2.1

jobs:
  packer:
    docker:
      - image: hashicorp/packer:full-1.7.9
    steps:
      - checkout
      - run:
          command: packer fmt .
          working_directory: images

  terraform:
    docker:
      - image: hashicorp/terraform:1.1.6
    steps:
      - checkout
      - run: terraform fmt -recursive

workflows:
  main:
    jobs:
      - packer
      - terraform
