version: 2.1

orbs: 
  terraform: circleci/terraform@3.0.1

jobs:
  packer:
    docker:
      - image: hashicorp/packer:full-1.7.9
    steps:
      - checkout
      - run:
          command: packer fmt .
          working_directory: images

  terraform:
    executor:
      name: terraform/default
      tag: 1.1.6
    steps:
      - checkout
      - terraform/fmt:
          path: terraform-aws-dedicated-hosts
      - terraform/fmt:
          path: terraform-aws-ec2-mac
      - terraform/validate:
          path: terraform-aws-dedicated-hosts

workflows:
  main:
    jobs:
      - packer
      - terraform
