version: 2.1

jobs:
  packer:
    docker:
      - image: hashicorp/packer:full-1.7.9
    steps:
      - checkout
      # Ruby Orb(Install fastlane)
      - run:
          command: |
            packer fmt .
            packer validate .
          working_directory: images

workflows:
  main:
    jobs:
      - packer
