version: 2.1

jobs:
  packer:
    docker:
      - image: hashicorp/packer:full-1.7.9
    steps:
      - checkout
      - run:
          command: packer fmt .
          working_directory: images

workflows:
  main:
    jobs:
      - packer
