---
- name: Mac Setup
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks
  hosts: 127.0.0.1
  connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/become.html#id1
  # become: yes
  vars:
    brew_taps:
      - homebrew/core
      - homebrew/cask
    brew_cask_apps:
      - alfred
      - clipy
      - docker
      - firefox
      - google-chrome
      - google-japanese-ime
      - google-hangouts
      - iterm2
      - licecap
      - snip
      - visual-studio-code
    brew_packages:
      - autoconf
      - awscli
      - bash-completion
      - docker-compose
      - docker-machine
      - doxygen
      - git
      - git-lfs
      - jq
      - nmap
      - openssl
      - ssh-copy-id
      - tig
      - tree
      - wget
      - zsh
      - zsh-syntax-highlighting

  # pre_tasks:
    ## https://brew.sh/
    # - name: Install Homebrew
    #   command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

  tasks:
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_tap_module.html
    - name: Homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_cask_module.html
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_apps }}"

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
