---
- name: EC2 Mac Setup
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks
  hosts: 127.0.0.1
  connection: local
  # https://docs.ansible.com/ansible/latest/user_guide/become.html#id1
  # become: yes
  vars:
    brew_taps:
      - robotsandpencils/made
    brew_packages:
      - xcodes
      - ruby-build

  tasks:
    # https://docs.ansible.com/ansible/2.7/modules/homebrew_tap_module.html
    - name: Homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"

    # https://docs.ansible.com/ansible/2.7/modules/homebrew_module.html
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"

    # - name: Install xcode-install gem
    #   gem:
    #     name: xcode-install
    #     include_doc: false
    #     user_install: false
    #     state: latest
    #     executable: /usr/bin/gem
    #   become: true

    # - name: Install Xcode 13.2.1
    #   xcode:
    #     version: "{{ xcode_version }}"
    #   environment:
    #     GEM_HOME: "{{ system_gem_dir }}"
    #     GEM_PATH: "{{ system_gem_dir }}"
    #     XCODE_INSTALL_USER: "{{ xcode_install_user }}"
    #     XCODE_INSTALL_PASSWORD: "{{ xcode_install_password }}"
